# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-02 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BarCodeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('dependence', models.CharField(max_length=255)),
                ('headquarters', models.CharField(max_length=255)),
                ('bar_code', models.ImageField(blank=True, null=True, upload_to='bar_code')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
            ],
            options={
                'db_table': 'bar_codes',
            },
        ),
    ]
